
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analysis;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int PAR_DER = 47;
  public static final int KW_FALSE = 33;
  public static final int POT = 8;
  public static final int MULT = 36;
  public static final int KW_INT = 18;
  public static final int EQUALS = 9;
  public static final int ENTERO = 4;
  public static final int KW_FOR = 27;
  public static final int XOR = 44;
  public static final int KW_DO = 28;
  public static final int DOS_PUNTOS = 53;
  public static final int KW_DOUBLE = 19;
  public static final int KW_CHAR = 21;
  public static final int CORCHETE_DER = 51;
  public static final int KW_CONST = 16;
  public static final int KW_PRINTLN = 31;
  public static final int LLAVE_IZQ = 48;
  public static final int NOT = 45;
  public static final int AND = 43;
  public static final int IGUAL = 39;
  public static final int CARACTER = 3;
  public static final int OR = 42;
  public static final int KW_MATCH = 25;
  public static final int DIV = 37;
  public static final int INCREMENTO = 14;
  public static final int UMENOS = 7;
  public static final int PUNTO_COMA = 52;
  public static final int KW_BOOL = 20;
  public static final int ID = 6;
  public static final int KW_CONTINUE = 30;
  public static final int EOF = 0;
  public static final int DECIMAL = 5;
  public static final int DECREMENTO = 15;
  public static final int error = 1;
  public static final int COMA = 55;
  public static final int CADENA = 2;
  public static final int MENOS = 35;
  public static final int DIF = 10;
  public static final int MAYOR_QUE = 41;
  public static final int MOD = 38;
  public static final int PAR_IZQ = 46;
  public static final int KW_TRUE = 32;
  public static final int KW_IF = 23;
  public static final int GUION_BAJO = 54;
  public static final int LLAVE_DER = 49;
  public static final int KW_BREAK = 29;
  public static final int CASTEO_PREC = 13;
  public static final int CORCHETE_IZQ = 50;
  public static final int MAYOR_IGUAL = 12;
  public static final int KW_ELSE = 24;
  public static final int KW_STRING = 22;
  public static final int KW_VAR = 17;
  public static final int MENOR_QUE = 40;
  public static final int KW_WHILE = 26;
  public static final int MENOR_IGUAL = 11;
  public static final int MAS = 34;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CADENA",
  "CARACTER",
  "ENTERO",
  "DECIMAL",
  "ID",
  "UMENOS",
  "POT",
  "EQUALS",
  "DIF",
  "MENOR_IGUAL",
  "MAYOR_IGUAL",
  "CASTEO_PREC",
  "INCREMENTO",
  "DECREMENTO",
  "KW_CONST",
  "KW_VAR",
  "KW_INT",
  "KW_DOUBLE",
  "KW_BOOL",
  "KW_CHAR",
  "KW_STRING",
  "KW_IF",
  "KW_ELSE",
  "KW_MATCH",
  "KW_WHILE",
  "KW_FOR",
  "KW_DO",
  "KW_BREAK",
  "KW_CONTINUE",
  "KW_PRINTLN",
  "KW_TRUE",
  "KW_FALSE",
  "MAS",
  "MENOS",
  "MULT",
  "DIV",
  "MOD",
  "IGUAL",
  "MENOR_QUE",
  "MAYOR_QUE",
  "OR",
  "AND",
  "XOR",
  "NOT",
  "PAR_IZQ",
  "PAR_DER",
  "LLAVE_IZQ",
  "LLAVE_DER",
  "CORCHETE_IZQ",
  "CORCHETE_DER",
  "PUNTO_COMA",
  "DOS_PUNTOS",
  "GUION_BAJO",
  "COMA"
  };
}

